server:
  port: 7956
  
spring:
  application:
    name: fzz-could-lockingSystem
  datasource:
        name: fzzmycat 
        url: jdbc:mysql://120.78.91.243:3310/fzzmycat?allowMultiQueries=true 
        username: root
        password: rootfzz

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  redis:
        # Redis服务器地址
        host: 47.106.207.56
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password:
        # 连接超时时间（毫秒）
        timeout: 0
        # Redis数据库索引（默认为0）
        database: 0
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0 
      
  activemq:
        brokerUrl: tcp://120.79.15.123:61616
        in-memory: true
        user: admin
        password: admin
        pool:
          enabled: false 
          idle-timeout: 30
          max-connections: 1
          maximum-active-session-per-connection: 500      
  jms:
    pub-sub-domain: true    
          
      
mybatis:
  mapper-locations: mapper/*/*.xml
  type-aliases-package: com.fzz.cloud.fzzcloudlockingSystem.entity.*

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql
    
#fastDFS配置

fdfs:
  soTimeout: 30
  connectTimeout: 60
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 47.106.207.56:22122


#配置日志
logging:
  #配置日志文件路径
  path: E:\log
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error   
    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1 
   

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      #defaultZone: http://user:password123@120.79.15.123:8764/eureka
      #defaultZone: http://user:password123@192.168.0.148:8764/eureka
      defaultZone: http://user:password123@localhost:8764/eureka